'use strict';


module.exports = {

  // go to beta.developer.spotify.com and register an app...
  // then fill in these below
  CLIENT_ID: 'REPLACE_WITH_YOUR_CLIENT_ID'.
  CLIENT_SECRET: 'REPLACE_WITH_YOUR_CLIENT_SECRET',

  // this is generated by you and totally random
  ENCRYPTION_SECRET: 'REPLACE_WITH_A_RANDOM_STRING_HERE_FOR_SALT'

  // this is the client callback youu allow in your ios URLSchemes and
  // register on the spotify developer console.
  CLIENT_CALLBACK: 'oauth-example://spotify'
};